<a href="https://www.kaggle.com/code/seshasaibellamkonda/my-first-comp?scriptVersionId=223871117" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd

In [2]:
food = pd.read_csv("/kaggle/input/messy-food-waste-prediction-dataset/test.csv", parse_dates=["date"],date_format="%Y-%m-%d")

In [3]:
food.head()

,ID,date,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg,staff_experience,waste_category
0,0,2022-12-19,196,13,27.887273,45.362854,0,0,7.740587,intermediate,dairy
1,1,2023-11-21,244,15,10.317872,64.430475,1,0,42.311779,NaN,MeAt
2,4,2022-02-01,148,16,27.714300,69.046113,1,0,41.184305,Beginner,MeAt
3,5,2023-03-19,157,19,19.173902,46.292823,6,0,41.543492,Beginner,MeAt
4,6,2022-07-18,297,10,26.375233,79.741064,0,0,26.525097,Intermediate,MEAT

In [4]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                911 non-null    int64
 1   date              911 non-null    datetime64[ns]
 2   meals_served      911 non-null    int64
 3   kitchen_staff     911 non-null    int64
 4   temperature_C     911 non-null    float64
 5   humidity_percent  911 non-null    float64
 6   day_of_week       911 non-null    int64
 7   special_event     911 non-null    int64
 8   past_waste_kg     911 non-null    float64
 9   staff_experience  747 non-null    object
 10  waste_category    911 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(5), object(2)
memory usage: 78.4+ KB

In [5]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                911 non-null    int64
 1   date              911 non-null    datetime64[ns]
 2   meals_served      911 non-null    int64
 3   kitchen_staff     911 non-null    int64
 4   temperature_C     911 non-null    float64
 5   humidity_percent  911 non-null    float64
 6   day_of_week       911 non-null    int64
 7   special_event     911 non-null    int64
 8   past_waste_kg     911 non-null    float64
 9   staff_experience  747 non-null    object
 10  waste_category    911 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(5), object(2)
memory usage: 78.4+ KB

In [6]:
col_new_names = {
    "date": "Date",
    "meals_served": "Meals_Served",
    "kitchen_staff": "Kitchen_Staff",
    "temperature_C": "Temperature_Celsius",
    "humidity_percent": "Humidity_Percent",
    "day_of_week": "Day_of_Week",
    "special_event": "Special_Event",
    "past_waste_kg": "Past_Waste_Kg",
    "staff_experience": "Staff_Experience",
    "waste_category": "Waste_Category"
}
food = food.rename(columns= col_new_names)

In [7]:
food.head()

,ID,Date,Meals_Served,Kitchen_Staff,Temperature_Celsius,Humidity_Percent,Day_of_Week,Special_Event,Past_Waste_Kg,Staff_Experience,Waste_Category
0,0,2022-12-19,196,13,27.887273,45.362854,0,0,7.740587,intermediate,dairy
1,1,2023-11-21,244,15,10.317872,64.430475,1,0,42.311779,NaN,MeAt
2,4,2022-02-01,148,16,27.714300,69.046113,1,0,41.184305,Beginner,MeAt
3,5,2023-03-19,157,19,19.173902,46.292823,6,0,41.543492,Beginner,MeAt
4,6,2022-07-18,297,10,26.375233,79.741064,0,0,26.525097,Intermediate,MEAT

In [8]:
food["Staff_Experience"].mode()

0    Beginner
Name: Staff_Experience, dtype: object

## lets replace NaN values in Staf_Experience with the mode value i.e, Beginner

In [9]:
food["Staff_Experience"] = food["Staff_Experience"].fillna("Beginner")

In [10]:
food["Staff_Experience"].unique()

array(['intermediate', 'Beginner', 'Intermediate', 'EXPERT'], dtype=object)

## lets correct the Intermediate and intermediate in to  a proper format

In [11]:
food["Staff_Experience"] = food["Staff_Experience"].replace("intermediate","Intermediate")

In [12]:
food.head()

,ID,Date,Meals_Served,Kitchen_Staff,Temperature_Celsius,Humidity_Percent,Day_of_Week,Special_Event,Past_Waste_Kg,Staff_Experience,Waste_Category
0,0,2022-12-19,196,13,27.887273,45.362854,0,0,7.740587,Intermediate,dairy
1,1,2023-11-21,244,15,10.317872,64.430475,1,0,42.311779,Beginner,MeAt
2,4,2022-02-01,148,16,27.714300,69.046113,1,0,41.184305,Beginner,MeAt
3,5,2023-03-19,157,19,19.173902,46.292823,6,0,41.543492,Beginner,MeAt
4,6,2022-07-18,297,10,26.375233,79.741064,0,0,26.525097,Intermediate,MEAT

## lets do the same with Waste_Category

In [13]:
food["Waste_Category"].unique()

array(['dairy', 'MeAt', 'MEAT', 'Vegetables', 'GRAINS'], dtype=object)

In [14]:
new_Waste_Categories = {
    "dairy": "Dairy",
    "MeAt": "Meat",
    "MEAT": "Meat",
    "Vegetables": "Vegetables",
    "GRAINS": "Grains"
}
food["Waste_Category"] = food["Waste_Category"].replace(new_Waste_Categories)

In [15]:
food["Waste_Category"].unique()

array(['Dairy', 'Meat', 'Vegetables', 'Grains'], dtype=object)

## lets convert the Waste_Category and Staff_Experience data type as category so we can same spme data and processing time

In [16]:
food["Waste_Category"] =food["Waste_Category"].astype("category")
food["Staff_Experience"] = food["Staff_Experience"].astype("category")

food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   911 non-null    int64
 1   Date                 911 non-null    datetime64[ns]
 2   Meals_Served         911 non-null    int64
 3   Kitchen_Staff        911 non-null    int64
 4   Temperature_Celsius  911 non-null    float64
 5   Humidity_Percent     911 non-null    float64
 6   Day_of_Week          911 non-null    int64
 7   Special_Event        911 non-null    int64
 8   Past_Waste_Kg        911 non-null    float64
 9   Staff_Experience     911 non-null    category
 10  Waste_Category       911 non-null    category
dtypes: category(2), datetime64[ns](1), float64(3), int64(5)
memory usage: 66.3 KB

In [17]:
food["Meals_Served"]

0      196
1      244
2      148
3      157
4      297
      ...
906    395
907    483
908    243
909    406
910    350
Name: Meals_Served, Length: 911, dtype: int64

## Lets replace not-normal temperatures in Temperature_Celsius with mediean of Temperature_Celsius

In [18]:
temp_min , temp_high = 10,45
food.loc[(food["Temperature_Celsius"] < temp_min) | (food["Temperature_Celsius"] > temp_high),"Temperature_Celsius"] = None
food["Temperature_Celsius"] = food["Temperature_Celsius"].fillna(food["Temperature_Celsius"].median())

In [19]:
food["Meals_Served"].describe()

count     911.000000
mean      375.405049
std       502.812717
min       100.000000
25%       211.000000
50%       306.000000
75%       407.000000
max      4730.000000
Name: Meals_Served, dtype: float64

In [20]:
max_meal_ser = 600
food.loc[(food["Meals_Served"]> max_meal_ser),"Meals_Served"]= None
food["Meals_Served"] = food["Meals_Served"].fillna(food["Meals_Served"].mean())

In [21]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   911 non-null    int64
 1   Date                 911 non-null    datetime64[ns]
 2   Meals_Served         911 non-null    float64
 3   Kitchen_Staff        911 non-null    int64
 4   Temperature_Celsius  911 non-null    float64
 5   Humidity_Percent     911 non-null    float64
 6   Day_of_Week          911 non-null    int64
 7   Special_Event        911 non-null    int64
 8   Past_Waste_Kg        911 non-null    float64
 9   Staff_Experience     911 non-null    category
 10  Waste_Category       911 non-null    category
dtypes: category(2), datetime64[ns](1), float64(4), int64(4)
memory usage: 66.3 KB

In [22]:
food = food.drop_duplicates()
food.reset_index(drop = True,inplace = True)

In [23]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   911 non-null    int64
 1   Date                 911 non-null    datetime64[ns]
 2   Meals_Served         911 non-null    float64
 3   Kitchen_Staff        911 non-null    int64
 4   Temperature_Celsius  911 non-null    float64
 5   Humidity_Percent     911 non-null    float64
 6   Day_of_Week          911 non-null    int64
 7   Special_Event        911 non-null    int64
 8   Past_Waste_Kg        911 non-null    float64
 9   Staff_Experience     911 non-null    category
 10  Waste_Category       911 non-null    category
dtypes: category(2), datetime64[ns](1), float64(4), int64(4)
memory usage: 66.3 KB

In [24]:
food.to_csv("/kaggle/working/final_submission.csv", index=False)